### ISSUE TITLE
andrion运行正常，ios运行报错

### ISSUE THREAD

**Issue by YangtaoWang** [Joker-388/flutter-geetest#3]
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
        
Error running pod install
Error launching application on iPhone 11 Pro Max.

git安装的插件是不是在CocoaPods中找不到？
大佬能不能发个flutter packages的包。

**Comment by Joker-388** [comment]
看这个错误提示是你的终端设置的问题啊，警告：CocoaPods需要你的终端使用UTF-8编码。
